package com.alongside.core.network.storage

import io.ktor.http.encodeURLParameter

/**
 * [bucket] is the Firebase Storage bucket host (e.g. "alongside-b05f2.firebasestorage.app"),
 * sourced the same way [com.alongside.core.network.firestore.FirestoreConfig]'s projectId is -
 * auto-generated by the Google Services Gradle plugin, not a `local.properties` entry. No
 * `apiKey` field: unlike Google Places/Gemini (third-party APIs), Storage REST auth is entirely
 * via the `Authorization` header (a Firebase-scheme bearer token), no query-string API key.
 *
 * Object path convention: flat `photos/{sanitized photoId}` - `Photo.id` is the local capture
 * URI itself (see `AndroidExifPhotoReader`), not a UUID, so it isn't safe to use verbatim as a
 * Storage object name: `content://...` URIs contain `://`, and Firebase Storage rejects object
 * names with consecutive slashes or a trailing slash. [sanitizeForObjectPath] maps every
 * character outside a safe set to `_`, keeping the mapping deterministic per id.
 */
public class FirebaseStorageConfig(
    public val bucket: String,
) {
    private val objectsBaseUrl: String get() = "https://firebasestorage.googleapis.com/v0/b/$bucket/o"

    public fun objectPath(photoId: String): String = "photos/${photoId.sanitizeForObjectPath()}"

    public fun uploadUrl(photoId: String): String = "$objectsBaseUrl?name=${objectPath(photoId).encodeURLParameter()}"

    public fun downloadUrl(
        photoId: String,
        downloadToken: String,
    ): String = "$objectsBaseUrl/${objectPath(photoId).encodeURLParameter()}?alt=media&token=$downloadToken"
}

private val UNSAFE_OBJECT_PATH_CHARACTERS = Regex("[^A-Za-z0-9_.-]")

private fun String.sanitizeForObjectPath(): String = replace(UNSAFE_OBJECT_PATH_CHARACTERS, "_")
