package com.alongside.androidapp.di

import android.content.Context
import com.alongside.core.database.AlongsideDatabase
import com.alongside.core.database.authSessionCache
import com.alongside.core.database.getDatabaseBuilder
import com.alongside.core.database.getRoomDatabase
import com.alongside.core.domain.auth.AuthSessionCache
import com.alongside.core.domain.auth.AuthSessionRepository
import com.alongside.core.domain.diary.processing.EpisodeVisionDescriptionClient
import com.alongside.core.domain.diary.processing.PhotoUploadClient
import com.alongside.core.domain.diary.processing.PlaceGeocodingClient
import com.alongside.core.domain.pairing.DefaultPairingRepository
import com.alongside.core.domain.pairing.InviteCodeGenerator
import com.alongside.core.domain.pairing.PairingRepository
import com.alongside.core.domain.place.importing.PlaceDetailsLookupClient
import com.alongside.core.domain.place.importing.PlaceImportPipeline
import com.alongside.core.domain.place.importing.PlacePhotoClient
import com.alongside.core.domain.place.importing.PlacePhotoUploadClient
import com.alongside.core.domain.place.importing.ShareLinkRedirectResolver
import com.alongside.core.network.auth.FirebaseAuthApi
import com.alongside.core.network.auth.FirebaseAuthConfig
import com.alongside.core.network.auth.FirebaseAuthSessionRepository
import com.alongside.core.network.auth.SessionFirestoreTokenProvider
import com.alongside.core.network.auth.asIdTokenRefresher
import com.alongside.core.network.client.createFirestoreHttpClient
import com.alongside.core.network.client.createShareLinkRedirectHttpClient
import com.alongside.core.network.firestore.FirestoreConfig
import com.alongside.core.network.firestore.FirestoreTokenProvider
import com.alongside.core.network.gemini.GeminiConfig
import com.alongside.core.network.gemini.GeminiVisionApi
import com.alongside.core.network.gemini.GeminiVisionDescriptionClient
import com.alongside.core.network.places.GooglePlacesConfig
import com.alongside.core.network.places.GooglePlacesDetailsApi
import com.alongside.core.network.places.GooglePlacesDetailsClient
import com.alongside.core.network.places.GooglePlacesGeocodingApi
import com.alongside.core.network.places.GooglePlacesGeocodingClient
import com.alongside.core.network.places.GooglePlacesPhotoApi
import com.alongside.core.network.places.GooglePlacesPhotoClient
import com.alongside.core.network.places.KtorShareLinkRedirectResolver
import com.alongside.core.network.storage.FirebasePlacePhotoUploadClient
import com.alongside.core.network.storage.FirebaseStorageApi
import com.alongside.core.network.storage.FirebaseStorageConfig
import com.alongside.core.network.storage.FirebaseStorageUploadClient
import com.alongside.feature.diary.capture.AndroidExifPhotoReader
import com.alongside.feature.diary.capture.AndroidPhotoByteReader
import com.alongside.feature.diary.capture.AndroidPhotoCompressor
import com.alongside.feature.diary.capture.ExifPhotoReader
import com.alongside.feature.diary.capture.PhotoByteReader
import com.alongside.feature.diary.capture.PhotoCompressor
import org.koin.core.module.Module
import org.koin.dsl.module

/**
 * [context], [firebaseApiKey], [firebaseProjectId] and [storageBucket] all come from androidApp
 * itself (Context to build the Room database; the API key, project id and storage bucket from
 * string resources generated by google-services.json processing, which only runs in this module)
 * - passed in explicitly rather than resolved through Koin's Android context-injection, so this
 * stays plain and easy to follow. [googlePlacesApiKey]/[geminiApiKey] come from BuildConfig fields
 * sourced from local.properties (see docs/local-setup.md) - unlike Firebase, neither has an
 * auto-generated key delivery file.
 */
public fun androidAppModule(
    context: Context,
    firebaseApiKey: String,
    firebaseProjectId: String,
    storageBucket: String,
    googlePlacesApiKey: String,
    geminiApiKey: String,
) = module {
    single { createFirestoreHttpClient() }
    single { FirebaseAuthConfig(apiKey = firebaseApiKey) }
    single { FirestoreConfig(projectId = firebaseProjectId) }
    single { FirebaseAuthApi(get(), get()) }
    single<AuthSessionRepository> { FirebaseAuthSessionRepository(get()) }
    single { getRoomDatabase(getDatabaseBuilder(context)) }
    single<AuthSessionCache> { get<AlongsideDatabase>().authSessionCache() }
    single<FirestoreTokenProvider> {
        SessionFirestoreTokenProvider(get(), get<FirebaseAuthApi>().asIdTokenRefresher())
    }
    single { InviteCodeGenerator() }
    // PairingTripDataSource comes from dataModule (Room + Firestore) since M9.
    single<PairingRepository> { DefaultPairingRepository(get(), get()) }
    single { GooglePlacesConfig(apiKey = googlePlacesApiKey) }
    single { GooglePlacesGeocodingApi(get(), get()) }
    single<PlaceGeocodingClient> { GooglePlacesGeocodingClient(get()) }
    single { GeminiConfig(apiKey = geminiApiKey) }
    single { GeminiVisionApi(get(), get()) }
    single<EpisodeVisionDescriptionClient> { GeminiVisionDescriptionClient(get()) }
    single<ExifPhotoReader> { AndroidExifPhotoReader(context.contentResolver) }
    single<PhotoByteReader> { AndroidPhotoByteReader(context.contentResolver) }
    single { FirebaseStorageConfig(bucket = storageBucket) }
    single { FirebaseStorageApi(get(), get(), get()) }
    single<PhotoCompressor> { AndroidPhotoCompressor() }
    single<PhotoUploadClient> {
        val photoCompressor = get<PhotoCompressor>()
        FirebaseStorageUploadClient(
            api = get(),
            config = get(),
            compress = { bytes -> photoCompressor.compress(bytes) },
        )
    }
    placesBindings()
}

/**
 * The M13.2 share-link import seams - split out from [androidAppModule] purely to keep it under
 * detekt's `LongMethod` threshold, not because these bindings are conceptually separate.
 */
private fun Module.placesBindings() {
    single<ShareLinkRedirectResolver> { KtorShareLinkRedirectResolver(createShareLinkRedirectHttpClient()) }
    single { GooglePlacesDetailsApi(get(), get()) }
    single<PlaceDetailsLookupClient> { GooglePlacesDetailsClient(get()) }
    single { GooglePlacesPhotoApi(get(), get()) }
    single<PlacePhotoClient> { GooglePlacesPhotoClient(get()) }
    single<PlacePhotoUploadClient> { FirebasePlacePhotoUploadClient(get(), get()) }
    single { PlaceImportPipeline(get(), get(), get(), get(), get()) }
}
