package com.alongside.androidapp.di

import android.content.Context
import com.alongside.core.database.AlongsideDatabase
import com.alongside.core.database.authSessionCache
import com.alongside.core.database.getDatabaseBuilder
import com.alongside.core.database.getRoomDatabase
import com.alongside.core.domain.auth.AuthSessionCache
import com.alongside.core.domain.auth.AuthSessionRepository
import com.alongside.core.network.auth.FirebaseAuthApi
import com.alongside.core.network.auth.FirebaseAuthConfig
import com.alongside.core.network.auth.FirebaseAuthSessionRepository
import com.alongside.core.network.client.createFirestoreHttpClient
import org.koin.dsl.module

/**
 * [context] and [firebaseApiKey] both come from androidApp itself (Context to build the Room
 * database; the API key from [com.alongside.androidapp.R.string.google_api_key], generated by
 * google-services.json processing, which only runs in this module) - passed in explicitly rather
 * than resolved through Koin's Android context-injection, so this stays plain and easy to follow.
 */
public fun androidAppModule(
    context: Context,
    firebaseApiKey: String,
) = module {
    single { createFirestoreHttpClient() }
    single { FirebaseAuthConfig(apiKey = firebaseApiKey) }
    single { FirebaseAuthApi(get(), get()) }
    single<AuthSessionRepository> { FirebaseAuthSessionRepository(get()) }
    single { getRoomDatabase(getDatabaseBuilder(context)) }
    single<AuthSessionCache> { get<AlongsideDatabase>().authSessionCache() }
}
